version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: task"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type: task"

  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type: task"
