repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  # Gateway Service Hooks
  - repo: local
    hooks:
      - id: format-gateway
        name: format-gateway
        entry: bash -c "cd gateway && bash scripts/format.sh"
        language: system
        pass_filenames: false
        files: ^gateway/

      - id: lint-gateway
        name: lint-gateway
        entry: bash -c "cd gateway && bash scripts/lint.sh"
        language: system
        pass_filenames: false
        files: ^gateway/

  # Auth Server Hooks
  - repo: local
    hooks:
      - id: format-auth-server
        name: format-auth-server
        entry: bash -c "cd auth-server && bash scripts/format.sh"
        language: system
        pass_filenames: false
        files: ^auth-server/

      - id: lint-auth-server
        name: lint-auth-server
        entry: bash -c "cd auth-server && bash scripts/lint.sh"
        language: system
        pass_filenames: false
        files: ^auth-server/

  # Test Hooks (TODO: Add test cases & hooks)
  # - repo: local
  #   hooks:
  #     - id: test-gateway
  #       name: test-gateway
  #       entry: bash -c "cd gateway && bash scripts/coverage-report.sh"
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       files: ^gateway/
  #
  #     - id: test-auth-server
  #       name: test-auth-server
  #       entry: bash -c "cd auth-server && bash scripts/coverage-report.sh"
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       files: ^auth-server/
